pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: "https://github.com/EugenMol/test_jenkins.git", branch: "main"
                }
            }
        stage('Check_Dockerfile') {
            steps {
                sh '''
                    docker info
                    docker run --rm -i hadolint/hadolint < Dockerfile
                '''
            }
        }
        stage('Build_Docker_Image') {
            steps {
                sh '''
                    docker build -t eugenmol86/test_docker_image .
                '''
            }
        }
        stage('Docker_Run') {
            steps {
                sh '''
                    docker run -d --rm -p 8081:80 --name test-jenkins eugenmol86/test_docker_image
                    echo $?
                    sleep 10
                    curl http://127.0.0.1:8081
                    docker stop $(docker ps -qf 'name=test-jenkins')
                '''
            }
        }
        stage('Docker_Push') {
            steps {
                sh '''
                    docker login -u "$DOCKER_REGISTRY_USER" -p $(echo $DOCKER_REGISTRY_PASSWORD | base64 -d) "$DOCKER_REGISTRY_SERVER"
                    docker push eugenmol86/test_docker_image
                '''
            }
        }
        stage('Deploying app in K8s') {
            steps {
                withKubeConfig([credentialsId: 'user-k8s') {
                    sh 'kubectl apply -f deployment.yml'
                }
            }
        }
        stage('Test'){
            steps {
            }
        }
        stage('Deploy') {
            steps {
            }
        }
    }
}
