---
- name: Site playbook
  hosts: host1
  gather_facts: yes
  become: yes
  roles:
    - web_server
#  tasks: 
#    - name: Set authorized key taken from file
#      ansible.posix.authorized_key:
#        user:  eugen
#        state: present
#        key:   "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
