
---
# tasks file for web_server
- name: Set authorized key taken from file
  authorized_key: 
    user:  root
    state: present
    key:   "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: Install package
  apt:
    name:         nginx
    state:        present
    update_cache: yes
- name: Copy nginx.conf to destination host
  template:
    src:  nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: "Restart nginx"
  when: ansible_facts['os_family'] == "Debian"
