name: Send message to TG

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo $(date) >> OUT
      - run: echo "${{github.actor}}" >> OUT
      - run: curl -s -X POST https://api.telegram.org/bot6243277711:AAH_wKjOAlUXvx5-7QFk8nwVaVnWFnffuEg/sendMessage -d chat_id=484531348 -d text="$(cat OUT)"
